In [19]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
import os

In [22]:
all_route = pd.read_csv("80mRoute.csv")
all_route

       Unnamed: 0     ele        lat         lon      distance     temp
0               0  38.688 -12.466018  130.842784  0.000000e+00      0.0
1              10  40.116 -12.465523  130.842627  8.069656e+01      1.0
2              16  39.141 -12.464773  130.843397  1.991709e+02      2.0
3              18  37.385 -12.464375  130.843787  2.604598e+02      3.0
4              22  36.143 -12.463871  130.844295  3.391211e+02      4.0
...           ...     ...        ...         ...           ...      ...
22128       38118  58.375 -34.927461  138.622595  3.037944e+06  37974.0
22129       38195  58.289 -34.927710  138.622494  3.038001e+06  37975.0
22130       38201  59.254 -34.927642  138.621605  3.038084e+06  37976.0
22131       38207  57.991 -34.927589  138.620574  3.038179e+06  37977.0
22132       38208  55.831 -34.927662  138.619010  3.038321e+06  37979.0

[22133 rows x 6 columns]

In [23]:
max_d = 0
tmp = 0

for row in all_route.index:
    if row == 0:
        continue
    
    if max_d < all_route.loc[row, 'distance'] - all_route.loc[row-1, 'distance']:
        max_d = all_route.loc[row, 'distance'] - all_route.loc[row-1, 'distance']
        shipsheki = row
    
    if all_route.loc[row, 'distance'] - all_route.loc[row-1, 'distance'] > 80:
        tmp += 1
    
print(max_d, shipsheki, tmp)

3633.059875387 9011 14818

In [24]:
all_route

       Unnamed: 0     ele        lat         lon      distance     temp
0               0  38.688 -12.466018  130.842784  0.000000e+00      0.0
1              10  40.116 -12.465523  130.842627  8.069656e+01      1.0
2              16  39.141 -12.464773  130.843397  1.991709e+02      2.0
3              18  37.385 -12.464375  130.843787  2.604598e+02      3.0
4              22  36.143 -12.463871  130.844295  3.391211e+02      4.0
...           ...     ...        ...         ...           ...      ...
22128       38118  58.375 -34.927461  138.622595  3.037944e+06  37974.0
22129       38195  58.289 -34.927710  138.622494  3.038001e+06  37975.0
22130       38201  59.254 -34.927642  138.621605  3.038084e+06  37976.0
22131       38207  57.991 -34.927589  138.620574  3.038179e+06  37977.0
22132       38208  55.831 -34.927662  138.619010  3.038321e+06  37979.0

[22133 rows x 6 columns]

In [25]:
diff = all_route['temp'].diff()
diff

0        NaN
1        1.0
2        1.0
3        1.0
4        1.0
        ...
22128    1.0
22129    1.0
22130    1.0
22131    1.0
22132    2.0
Name: temp, Length: 22133, dtype: float64